app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/home/MapViewFragment.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_map.xml
- close #5
- HomeFragment에 지도 SDK 연동 및 추가
=> Feature: HomeFragment 지도 생성 #5

app/src/main/java/com/pob/seeat/data/remote/AlarmRemote.kt
- 내가 작성한 댓글 알림의 경우 숨김 처리
- 아예 파이어스토어에서 알림을 삭제하는 방식으로 구현
=> Fix: 내가 작성한 댓글 알림의 경우 숨김 처리

app/src/main/AndroidManifest.xml, app/src/main/java/com/pob/seeat/data/remote/ReportCommentService.kt, app/src/main/java/com/pob/seeat/data/repository/ReportCommentRepository.kt, app/src/main/java/com/pob/seeat/di/ReportCommentModule.kt, app/src/main/java/com/pob/seeat/domain/model/CommentReportModel.kt, app/src/main/java/com/pob/seeat/domain/repository/ReportCommentRepositoryImpl.kt, app/src/main/java/com/pob/seeat/domain/usecase/ReportCommentUseCase.kt, app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt, app/src/main/java/com/pob/seeat/presentation/viewmodel/CommentViewModel.kt, app/src/main/java/com/pob/seeat/presentation/viewmodel/ReportCommentViewModel.kt
- 댓글 신고기능 추가했습니다
- 댓글 달자마자 삭제했을 때 앱 종료되는 버그 수정했슴당
=> 댓글신고기능 추가/ 버그 수정

app/src/main/java/com/pob/seeat/presentation/view/home/BottomSheetFeedAdapter.kt, app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/home/TagAdapter.kt, app/src/main/java/com/pob/seeat/utils/KoreanMatcher.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/values/strings.xml
- close #133 
- 홈 화면 게시물 제목 검색 기능 구현
- 홈 화면 게시물 태그 검색 기능 구현
- 검색 결과에 따라 마커 필터링 추가
=> 홈 화면 검색 기능 구현

app/src/main/java/com/pob/seeat/presentation/view/feed/NewFeedFragment.kt, app/src/main/java/com/pob/seeat/utils/Utils.kt, app/src/main/res/layout/item_image_upload.xml
- close #136 
- 이미지 업로드 시 회전되어서 나오는 문제를 해결
=> Feature add marker

app/src/main/java/com/pob/seeat/data/remote/CommentSource.kt, app/src/main/java/com/pob/seeat/data/remote/CommentSourceImpl.kt, app/src/main/java/com/pob/seeat/data/remote/FeedRemote.kt, app/src/main/java/com/pob/seeat/data/repository/CommentRepositoryImpl.kt, app/src/main/java/com/pob/seeat/di/UseCaseModule.kt, app/src/main/java/com/pob/seeat/domain/repository/CommentRepository.kt, app/src/main/java/com/pob/seeat/domain/usecase/CommentUseCases.kt, app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt, app/src/main/java/com/pob/seeat/presentation/viewmodel/CommentViewModel.kt, app/src/main/java/com/pob/seeat/utils/dialog/Dialog.kt, app/src/main/res/layout/my_comment_dialog.xml
=> Update: 댓글 수정버튼 없애버림

app/build.gradle.kts, app/src/main/java/com/pob/seeat/presentation/view/mypage/MyPageFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/mypage/history/HistoryFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/mypage/history/HistoryListFragment.kt, app/src/main/java/com/pob/seeat/presentation/viewmodel/MyPageSharedViewModel.kt, app/src/main/res/layout/fragment_history.xml, app/src/main/res/layout/fragment_history_list.xml, app/src/main/res/layout/fragment_my_page.xml, gradle/libs.versions.toml
- close #140 
- 마이페이지 당겨서 새로고침 기능 추가
=> 마이페이지 사용성 개선

app/src/main/java/com/pob/seeat/presentation/view/alarm/AlarmFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/bookmark/BookmarkFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/mypage/history/HistoryFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/mypage/history/HistoryListFragment.kt, app/src/main/res/layout/fragment_alarm.xml, app/src/main/res/layout/fragment_bookmark.xml, app/src/main/res/layout/fragment_history.xml, app/src/main/res/layout/fragment_history_list.xml, app/src/main/res/values/strings.xml
- close #141 
- 알림 화면, 북마크 화면, 마이페이지 목록에 아무 값도 없을 때의 디자인 추가
=> 목록이 비어있을 때의 디자인 추가

.idea/deploymentTargetSelector.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/pob/seeat/data/model/chat/ChatFeedInfoModel.kt, app/src/main/java/com/pob/seeat/data/model/chat/MessageModel.kt, app/src/main/java/com/pob/seeat/data/remote/FeedRemote.kt, app/src/main/java/com/pob/seeat/data/remote/chat/MessagesRemote.kt, app/src/main/java/com/pob/seeat/data/remote/chat/UsersRemote.kt, app/src/main/java/com/pob/seeat/data/repository/ChatListRepositoryImpl.kt, app/src/main/java/com/pob/seeat/data/repository/ChatRepositoryImpl.kt, app/src/main/java/com/pob/seeat/domain/repository/ChatListRepository.kt, app/src/main/java/com/pob/seeat/presentation/view/chat/ChatListFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/chat/ChattingActivity.kt, app/src/main/java/com/pob/seeat/presentation/view/chat/chatlist/adapter/ChatListAdapter.kt, app/src/main/java/com/pob/seeat/presentation/view/chat/chatlist/adapter/ChatListDiffUtil.kt, app/src/main/java/com/pob/seeat/presentation/view/chat/chatlist/viewholder/SuccessViewHolder.kt, app/src/main/java/com/pob/seeat/presentation/view/chat/items/ChatListUiItem.kt, app/src/main/java/com/pob/seeat/presentation/viewmodel/ChatListViewModel.kt, app/src/main/java/com/pob/seeat/presentation/viewmodel/ChatViewModel.kt, app/src/main/res/layout/item_chat_list.xml
- close #65
- 채팅 99.999999퍼센트 완료
=> Feature chat

app/src/main/java/com/pob/seeat/utils/Utils.kt
- 정확한 날짜 표시 없이 얼마나 지났는지만 표시하도록 변경
```kotlin
* - 1분 미만: 방금 전
* - 1분 이상 1시간 미만: n분 전
* - 1시간 이상 하루 미만: n시간 전
* - 하루 이상 일주일 미만: n일 전
* - 일주일 이상 한달 미만: n주 전
* - 한달 이상 1년 미만: n달 전
* - 1년 이상: n년 전
```
=> 날짜 표시 형식 변경

app/src/main/java/com/pob/seeat/data/remote/DetailFeed.kt, app/src/main/java/com/pob/seeat/data/remote/FeedRemote.kt, app/src/main/java/com/pob/seeat/data/remote/ReportFeedRemote.kt, app/src/main/java/com/pob/seeat/data/remote/SendReportFeed.kt, app/src/main/java/com/pob/seeat/data/repository/FeedRepositoryImpl.kt, app/src/main/java/com/pob/seeat/data/repository/ReportFeedRepositoryImpl.kt, app/src/main/java/com/pob/seeat/di/ReportFeedModule.kt, app/src/main/java/com/pob/seeat/domain/model/FeedReportModel.kt, app/src/main/java/com/pob/seeat/domain/repository/FeedRepository.kt, app/src/main/java/com/pob/seeat/domain/repository/ReportFeedRepository.kt, app/src/main/java/com/pob/seeat/domain/usecase/RemoveFeedUseCase.kt, app/src/main/java/com/pob/seeat/domain/usecase/ReportFeedUseCase.kt, app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt, app/src/main/java/com/pob/seeat/presentation/viewmodel/DetailViewModel.kt, app/src/main/res/layout/fragment_detail.xml, app/src/main/res/menu/menu_detail.xml, app/src/main/res/menu/menu_detail_another_user.xml, app/src/main/res/values/strings.xml
- close #137
- 디테일 화면에서 게시글 삭제 버튼 구현
- 디테일 화면에서 게시글 신고 버튼 구현
- 해당 사용자와 작성자가 같으면 삭제버튼이 보이고 다르면 신고버튼이 보임
=> Feature 게시글 신고 및 삭제 구현

app/src/main/java/com/pob/seeat/di/NaverMapModule.kt, app/src/main/java/com/pob/seeat/presentation/service/NaverMapWrapper.kt, app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/detail/ShowLocateFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/feed/NewFeedFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/feed/SelectLocateFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt, app/src/main/res/layout/fragment_show_locate.xml, app/src/main/res/navigation/main_navigation.xml, app/src/main/res/values/strings.xml
- 게시글 상세화면에서 위치 확인 버튼 클릭 시 해당 위치를 지도 마커로 확인 가능
=> Add show locate

app/src/main/java/com/pob/seeat/presentation/view/mypage/MyPageFragment.kt
=> Update: 프로필 업데이트 취소시 토스트메세지 변경

app/src/main/res/layout/activity_settings.xml
=> Design: 설정페이지 댓글/채팅 알림 설정 쪽 빼둠

app/src/main/java/com/pob/seeat/presentation/view/sign/LoginActivity.kt, app/src/main/java/com/pob/seeat/presentation/view/sign/SignUpActivity.kt, app/src/main/java/com/pob/seeat/presentation/view/sign/SignUpIntroduceFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/sign/SignUpNameFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/sign/SignUpPhotoFragment.kt, app/src/main/java/com/pob/seeat/utils/dialog/Dialog.kt, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/confirm_dialog.xml, app/src/main/res/layout/fragment_detail.xml, app/src/main/res/layout/fragment_sign_up_introduce.xml, app/src/main/res/layout/fragment_sign_up_name.xml, app/src/main/res/layout/fragment_sign_up_photo.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/style.xml
- 프로필 설정화면에서 스킵 기능 추가
- 로그인 액티비티에서 화면넘어갈 때 프로그래스 바 추가
- 디테일 페이지 UI수
=> Feature comment sort

app/src/main/java/com/pob/seeat/presentation/view/home/BottomSheetFeedAdapter.kt, app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt, app/src/main/java/com/pob/seeat/utils/KoreanMatcher.kt, app/src/main/res/layout/fragment_home.xml
- 게시물 목록을 받아오는 중에도 "검색 결과가 없습니다."라고 표시되는 현상 해결
- 게시물 목록을 받아올 때에는 프로그래스바가 표시되게 변경
- 게시물 목록 검색 기능 개선
=> 홈 화면 로딩바 추가

app/src/main/java/com/pob/seeat/MainActivity.kt, app/src/main/java/com/pob/seeat/domain/repository/FeedRepository.kt, app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/home/EmptyFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt, app/src/main/java/com/pob/seeat/presentation/viewmodel/HomeViewModel.kt, app/src/main/java/com/pob/seeat/utils/Utils.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_empty.xml, app/src/main/res/navigation/main_navigation.xml
- close #170 
- 다른 화면을 오갔을때 HomeFragment 상태 유지
=> Add back on detail

app/src/main/java/com/pob/seeat/presentation/view/chat/ChattingActivity.kt, app/src/main/java/com/pob/seeat/presentation/view/chat/ChattingFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/feed/NewFeedFragment.kt, app/src/main/res/layout/fragment_select_locate.xml
- close #174 
- 마커 재지정시 지도가 두개 보이는 버그 해결
=> Refactor add marker

app/src/main/res/layout/fragment_home.xml
=> Fix: indoorLevelPicker 위치 조정

app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt, app/src/main/java/com/pob/seeat/presentation/view/home/BottomSheetFeedAdapter.kt, app/src/main/res/drawable/ic_seed.xml, app/src/main/res/layout/fragment_detail.xml
=> Refactor detail view

app/src/main/res/values/strings.xml
=> Refactor: 위치보기 텍스트 밑줄 추가

app/src/main/java/com/pob/seeat/presentation/view/alarm/AlarmAdapter.kt, app/src/main/java/com/pob/seeat/presentation/view/alarm/AlarmFragment.kt, app/src/main/res/layout/fragment_alarm.xml, app/src/main/res/layout/item_alarm.xml, app/src/main/res/values/colors.xml
- close #185 
- 읽지 않은 알림 표시 방식 변경
- 알림 배경 색상 변경
- 텍스트 색상 회색 > 진한 회색 변경
=> Design: 알림 화면 디자인 피드백 반영

.idea/deploymentTargetSelector.xml, app/src/main/java/com/pob/seeat/data/model/UserInfo.kt, app/src/main/java/com/pob/seeat/data/remote/UserInfoSource.kt, app/src/main/java/com/pob/seeat/data/remote/UserInfoSourceImpl.kt, app/src/main/java/com/pob/seeat/data/repository/ChatRepositoryImpl.kt, app/src/main/java/com/pob/seeat/domain/model/UserInfoModel.kt, app/src/main/java/com/pob/seeat/presentation/view/mypage/settings/SettingsActivity.kt, app/src/main/java/com/pob/seeat/presentation/viewmodel/SettingViewModel.kt, app/src/main/res/layout/activity_settings.xml
=> Feat : Notification Setting

app/src/main/java/com/pob/seeat/data/remote/UserInfoSourceImpl.kt, app/src/main/java/com/pob/seeat/data/repository/UserInfoRepositoryImpl.kt, app/src/main/java/com/pob/seeat/domain/repository/UserInfoRepository.kt, app/src/main/java/com/pob/seeat/domain/usecase/UserInfoUseCases.kt, app/src/main/java/com/pob/seeat/presentation/view/admin/UserListFragment.kt, app/src/main/java/com/pob/seeat/presentation/viewmodel/AdminUserViewModel.kt, app/src/main/res/layout/layout_profile_bottom_sheet.xml, app/src/main/res/values/strings.xml
- close #194
- 사용자 정보 삭제 확인 다이얼로그 추가
- 사용자 정보 삭제 후 확인 메시지 추가
- 현재 로그인 한 관리자 계정은 삭제가 되지 않게 처리
=> Refactor: 유저 삭제 사용성 개선

app/src/main/java/com/pob/seeat/MainActivity.kt
- close #197
- 뒤로가기 눌러 앱 종료 기능 구현
=> 뒤로가기 눌러 앱 종료 기능 구현

app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt, app/src/main/res/layout/fragment_detail.xml
- close #203 
- 디테일화면 스와이프시 새로고침
=> Feature: detail 새로고침 추가 #203

app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt, app/src/main/res/layout/fragment_home.xml
- close 
- 바텀시트 따라서 버튼이 따라가도록 설정
=> Feature: bottomSheet 따라 버튼 올라가는 기능 추가 #203

app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt
=> BugFix: refresh 버튼 수정

app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt
=> Refactor: binding 코드수정

app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt, app/src/main/res/layout/fragment_detail.xml
=> 디테일화면 댓글 추가 레이아웃 안보이는 버그 해결

app/src/main/res/layout/fragment_detail.xml
=> Bug Fix: detail 댓글 등록 요소 다시 보이게 설정

app/src/main/java/com/pob/seeat/MainActivity.kt
=> 뒤로가기 동작 보완 

app/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml
- close #235
- firebase-crashlytics 적용
=> firebase-crashlytics SDK, 플러그인 추가
